/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dkrobghdkdahtiysvutg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcm9iZ2hka2RhaHRpeXN2dXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxNzQyOTksImV4cCI6MjA4OTc1MDI5OX0.QYooB-6Oi1czyObwjtbya2o6I03-VYlXlSrUqJgXoGA"