ALTER TABLE IF EXISTS notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sparks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pairings DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS albums (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  pair_id TEXT NOT NULL,
  author_id UUID REFERENCES auth.users(id),
  url TEXT NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS days_matter (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  pair_id TEXT NOT NULL,
  author_id UUID REFERENCES auth.users(id),
  title TEXT NOT NULL,
  date TEXT NOT NULL
);

ALTER TABLE IF EXISTS albums DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS days_matter DISABLE ROW LEVEL SECURITY;
